apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  role: Karpenter-pdp-eks-cluster
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: pdp-eks-cluster
  securityGroupSelectorTerms:
    - tags:
        kubernetes.io/cluster/pdp-eks-cluster: owned
