apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: juice-shop-jwt-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: juice-shop-jwt-secret
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: juice-shop/jwt-secret
        property: JWT_SECRET
